version: '3'

services:
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACK_API_URL: ${NEXT_PUBLIC_BACK_API_URL}
    env_file:
      - .env
    volumes:
      - ./front:/app
      - /app/.next
      - /app/node_modules
    ports:
      - "3020:3020"
    command: ${FRONT_RUN_COMMAND}

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./back:/app
    ports:
      - "3021:3021"
    command: ${BACK_RUN_COMMAND}
